### ISSUE TITLE
`--enablelockingrange 1` was not enough, needed `--setLockingRange 1 LK`

### ISSUE THREAD

**Issue by Demetrio92** [fornellas/tcg_opal_rootfs#5]
I was a bit baffled as to why my data is not encrypted. After doing some inspecting with `sedutil-cli --listLockingRanges` I figured that this set up somehow enabled the locking range to be in an RW mode. Maybe I was testing things in a live usb and set it this way manually, but it persisted. 

I'd recommend adding 

```
sedutil-cli --setLockingRange 1 LK $PASS $DEVICE
```

to the setup procedure

**Comment by fornellas** [comment]
The setup instructions do not indeed lock the device, but I recall testing them and powering off the machine, and it will indeed lock the device. This is just how SED is designed to work, while there's power, it keeps unlocked.

If we add a locking step, it is also required to ensure that all mounted filesystem on that region are umounted & the drive synced, otherwise, we risk corrupting data should anything be left on kernel buffer before the locking. While that's doable, I'm not sure about the installer, whether it'll be happy or not with the partitions being umounted externally (maybe yes?).

Addressing all of the above requires adding a fair amount of steps, for what IMHO, yields no gains. Perhaps just mentioning that after the first boot, one can poweroff the machine and confirm whether the password will be asked, though I feel like this is gonna happen anyway, so...

If you feel like there's a viable way, please cut a PR with your ideas.
